[default]
workshop = [
    "450814997",  # CBA_A3
    "463939057",  # ACE
    "1638341685", # DUI - Squad Radar
    "3499977893", # Advanced Dev Tools
    "623475643",  # 3DEN Enhanced
]
presets = []
dlc = []
optionals = []
parameters = []
mission = "DUI_CUSTOMIZATION.VR"
