name = "DUI Customization"
author = "DartRuffian"
prefix = "duic"
mainprefix = "z"

[version]
path = "addons/main/script_version.hpp"
git_hash = 0

[files]
include = [
    "mod.cpp",
    "meta.cpp",
    "logo_duic.png",
    "logo_duic_over.png",
    "logo_duic_ca.paa",
    "logo_duic_over_ca.paa",
    "LICENSE.md",
    "README.md",
]
exclude = []

[properties]
author = "DartRuffian"
